### ISSUE TITLE
Device back button Doesn't count previous screen / page which wrapped with the widget

### ISSUE THREAD

**Issue by Mu7ammadRasul** [NaagAlgates/flutter_no_internet_widget#17]
while pressing back button on the device it doesn't store previous screen from the cache history instead it always pops into very start of the page that app starts with, in my case it skipped 3 screens!

**Comment by NaagAlgates** [comment]
Yes. Currently, it doesn't support it. I will work on that feature and will add it soon. Thank you for reporting an issue.

**Comment by Mu7ammadRasul** [comment]
> Yes. Currently, it doesn't support it. I will work on that feature and will add it soon. Thank you for reporting an issue.

NP, hope you give an update as my App is completely done except for that package is a huge stepdown for me unless a fix is on the way i would really appreciate it.

**Comment by NaagAlgates** [comment]
I'm working on it and will provide a new dev version soon.

**Comment by NaagAlgates** [comment]
The new version has no support for the back button yet. But the previous screen is stored, and when it is online, you can see the old screen instead of opening the very first screen.

For example:
You navigated to, 
* Splashscreen
* Login Screen
* Home Screen
* Accounts Screen

Now let's say there is no internet after navigating to the Accounts screen, and a new full screen (No internet screen) is displayed.

** After a few seconds, the internet is back. **

You will see the "Accounts screen" rather than the Home Screen.
